### PR TITLE
Closes #1 create initial index.html

### LINKED ISSUE #1: create initial index.html

### PR DESCRIPTION
**Pull request by Denbuvalyy**

### CODE REVIEW

**Review by nazar-kotsun — CHANGES_REQUESTED** [review]
Please add content to index.html

**Review by dreamofmaks — CHANGES_REQUESTED** [review]
Add content to the file

**Review by bogdangavrylyak — APPROVED** [review]
Add something

**Review by bogdangavrylyak — CHANGES_REQUESTED** [review]
Add sth

**Review by dreamofmaks — APPROVED** [review]
Good job

**Review by nazar-kotsun — APPROVED** [review]
Good

**Review by bogdangavrylyak — APPROVED** [review]
Good job

**Pull request merged**
